#!/bin/bash

cat before_inj.cu > cs_motif_test1.cu
cat cs_motif_test1_inject.cu >> cs_motif_test1.cu
cat after_inj.cu >> cs_motif_test1.cu
cat before_inj.cu > cs_motif_test2.cu
cat cs_motif_test2_inject.cu >> cs_motif_test2.cu
cat after_inj.cu >> cs_motif_test2.cu
cat before_inj.cu > cs_motif_test3.cu
cat cs_motif_test3_inject.cu >> cs_motif_test3.cu
cat after_inj.cu >> cs_motif_test3.cu
cat before_inj.cu > cs_motif_test4.cu
cat cs_motif_test4_inject.cu >> cs_motif_test4.cu
cat after_inj.cu >> cs_motif_test4.cu
cat before_inj.cu > cs_motif_test5.cu
cat cs_motif_test5_inject.cu >> cs_motif_test5.cu
cat after_inj.cu >> cs_motif_test5.cu
cat before_inj.cu > cs_motif_test6.cu
cat cs_motif_test6_inject.cu >> cs_motif_test6.cu
cat after_inj.cu >> cs_motif_test6.cu
cat before_inj.cu > cs_motif_test7.cu
cat cs_motif_test7_inject.cu >> cs_motif_test7.cu
cat after_inj.cu >> cs_motif_test7.cu
cat before_inj.cu > cs_motif_test8.cu
cat cs_motif_test8_inject.cu >> cs_motif_test8.cu
cat after_inj.cu >> cs_motif_test8.cu

cat before_inj.cu > mc_motif_test1.cu
cat mc_motif_test1_inject.cu >> mc_motif_test1.cu
cat after_inj.cu >> mc_motif_test1.cu
cat before_inj.cu > mc_motif_test2.cu
cat mc_motif_test2_inject.cu >> mc_motif_test2.cu
cat after_inj.cu >> mc_motif_test2.cu
cat before_inj.cu > mc_motif_test3.cu
cat mc_motif_test3_inject.cu >> mc_motif_test3.cu
cat after_inj.cu >> mc_motif_test3.cu
cat before_inj.cu > mc_motif_test4.cu
cat mc_motif_test4_inject.cu >> mc_motif_test4.cu
cat after_inj.cu >> mc_motif_test4.cu
cat before_inj.cu > mc_motif_test5.cu
cat mc_motif_test5_inject.cu >> mc_motif_test5.cu
cat after_inj.cu >> mc_motif_test5.cu
cat before_inj.cu > mc_motif_test6.cu
cat mc_motif_test6_inject.cu >> mc_motif_test6.cu
cat after_inj.cu >> mc_motif_test6.cu
cat before_inj.cu > mc_motif_test7.cu
cat mc_motif_test7_inject.cu >> mc_motif_test7.cu
cat after_inj.cu >> mc_motif_test7.cu
cat before_inj.cu > mc_motif_test8.cu
cat mc_motif_test8_inject.cu >> mc_motif_test8.cu
cat after_inj.cu >> mc_motif_test8.cu

cat before_inj.cu > wv_motif_test1.cu
cat wv_motif_test1_inject.cu >> wv_motif_test1.cu
cat after_inj.cu >> wv_motif_test1.cu
cat before_inj.cu > wv_motif_test2.cu
cat wv_motif_test2_inject.cu >> wv_motif_test2.cu
cat after_inj.cu >> wv_motif_test2.cu
cat before_inj.cu > wv_motif_test3.cu
cat wv_motif_test3_inject.cu >> wv_motif_test3.cu
cat after_inj.cu >> wv_motif_test3.cu
cat before_inj.cu > wv_motif_test4.cu
cat wv_motif_test4_inject.cu >> wv_motif_test4.cu
cat after_inj.cu >> wv_motif_test4.cu
cat before_inj.cu > wv_motif_test5.cu
cat wv_motif_test5_inject.cu >> wv_motif_test5.cu
cat after_inj.cu >> wv_motif_test5.cu
cat before_inj.cu > wv_motif_test6.cu
cat wv_motif_test6_inject.cu >> wv_motif_test6.cu
cat after_inj.cu >> wv_motif_test6.cu
cat before_inj.cu > wv_motif_test7.cu
cat wv_motif_test7_inject.cu >> wv_motif_test7.cu
cat after_inj.cu >> wv_motif_test7.cu
cat before_inj.cu > wv_motif_test8.cu
cat wv_motif_test8_inject.cu >> wv_motif_test8.cu
cat after_inj.cu >> wv_motif_test8.cu

cat before_inj.cu > pt_motif_test1.cu
cat pt_motif_test1_inject.cu >> pt_motif_test1.cu
cat after_inj.cu >> pt_motif_test1.cu
cat before_inj.cu > pt_motif_test2.cu
cat pt_motif_test2_inject.cu >> pt_motif_test2.cu
cat after_inj.cu >> pt_motif_test2.cu
cat before_inj.cu > pt_motif_test3.cu
cat pt_motif_test3_inject.cu >> pt_motif_test3.cu
cat after_inj.cu >> pt_motif_test3.cu
cat before_inj.cu > pt_motif_test4.cu
cat pt_motif_test4_inject.cu >> pt_motif_test4.cu
cat after_inj.cu >> pt_motif_test4.cu
cat before_inj.cu > pt_motif_test5.cu
cat pt_motif_test5_inject.cu >> pt_motif_test5.cu
cat after_inj.cu >> pt_motif_test5.cu
cat before_inj.cu > pt_motif_test6.cu
cat pt_motif_test6_inject.cu >> pt_motif_test6.cu
cat after_inj.cu >> pt_motif_test6.cu
cat before_inj.cu > pt_motif_test7.cu
cat pt_motif_test7_inject.cu >> pt_motif_test7.cu
cat after_inj.cu >> pt_motif_test7.cu
cat before_inj.cu > pt_motif_test8.cu
cat pt_motif_test8_inject.cu >> pt_motif_test8.cu
cat after_inj.cu >> pt_motif_test8.cu

cat before_inj.cu > or_motif_test1.cu
cat or_motif_test1_inject.cu >> or_motif_test1.cu
cat after_inj.cu >> or_motif_test1.cu
cat before_inj.cu > or_motif_test2.cu
cat or_motif_test2_inject.cu >> or_motif_test2.cu
cat after_inj.cu >> or_motif_test2.cu
cat before_inj.cu > or_motif_test3.cu
cat or_motif_test3_inject.cu >> or_motif_test3.cu
cat after_inj.cu >> or_motif_test3.cu
cat before_inj.cu > or_motif_test4.cu
cat or_motif_test4_inject.cu >> or_motif_test4.cu
cat after_inj.cu >> or_motif_test4.cu
cat before_inj.cu > or_motif_test5.cu
cat or_motif_test5_inject.cu >> or_motif_test5.cu
cat after_inj.cu >> or_motif_test5.cu
cat before_inj.cu > or_motif_test6.cu
cat or_motif_test6_inject.cu >> or_motif_test6.cu
cat after_inj.cu >> or_motif_test6.cu
cat before_inj.cu > or_motif_test7.cu
cat or_motif_test7_inject.cu >> or_motif_test7.cu
cat after_inj.cu >> or_motif_test7.cu
cat before_inj.cu > or_motif_test8.cu
cat or_motif_test8_inject.cu >> or_motif_test8.cu
cat after_inj.cu >> or_motif_test8.cu

cat before_inj.cu > lj_motif_test1.cu
cat lj_motif_test1_inject.cu >> lj_motif_test1.cu
cat after_inj.cu >> lj_motif_test1.cu
cat before_inj.cu > lj_motif_test2.cu
cat lj_motif_test2_inject.cu >> lj_motif_test2.cu
cat after_inj.cu >> lj_motif_test2.cu
cat before_inj.cu > lj_motif_test3.cu
cat lj_motif_test3_inject.cu >> lj_motif_test3.cu
cat after_inj.cu >> lj_motif_test3.cu
cat before_inj.cu > lj_motif_test4.cu
cat lj_motif_test4_inject.cu >> lj_motif_test4.cu
cat after_inj.cu >> lj_motif_test4.cu
cat before_inj.cu > lj_motif_test5.cu
cat lj_motif_test5_inject.cu >> lj_motif_test5.cu
cat after_inj.cu >> lj_motif_test5.cu
cat before_inj.cu > lj_motif_test6.cu
cat lj_motif_test6_inject.cu >> lj_motif_test6.cu
cat after_inj.cu >> lj_motif_test6.cu
cat before_inj.cu > lj_motif_test7.cu
cat lj_motif_test7_inject.cu >> lj_motif_test7.cu
cat after_inj.cu >> lj_motif_test7.cu
cat before_inj.cu > lj_motif_test8.cu
cat lj_motif_test8_inject.cu >> lj_motif_test8.cu
cat after_inj.cu >> lj_motif_test8.cu
